name: Build testformycode for ARMv7

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download source code
      run: |
        wget https://ebook.wku.ac.kr/ftp/titanbooks/_upload/testformycode.zip
        unzip testformycode.zip
        cd testformycode

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang \
          libuv1-dev \
          libhwloc-dev \
          libssl-dev \
          pkg-config \
          git

    - name: Build testformycode
      run: |
        cd testformycode
        mkdir build
        cd build
        cmake .. \
          -DBUILD_STATIC=ON \
          -Dtestformycode_DEPS=<path to precompiled dependencies> \
          -DARM_TARGET=7 \
          -DUV_INCLUDE_DIR=/usr/include \
          -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.so \
          -DHWLOC_INCLUDE_DIR=/usr/include \
          -DHWLOC_LIBRARY=/usr/lib/x86_64-linux-gnu/libhwloc.so \
          -DOPENSSL_ROOT_DIR=/usr \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++
        make

    - name: Upload ARMv7 build
      uses: actions/upload-artifact@v3
      with:
        name: xmr-armv7
        path: build/testformycode # 假设编译后的文件名为 testformycode
