name: Build testformycode for ARMv7

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Download source code
        run: |
          wget -O testformycode.zip http://8.138.123.18:8180/testformycode.zip
          unzip testformycode.zip
          cd testformycode

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ARMv7 testformycode Docker image
        run: |
          # 创建并使用 Buildx 实例
          docker buildx create --use

          # 构建 Docker 镜像，指定 ARMv7 平台
          docker buildx build --platform linux/arm/v7 -t testformycode:armv7 .

      - name: Build and run testformycode
        run: |
          docker run --rm \
            --platform linux/arm/v7 \
            -v ${{ github.workspace }}/testformycode:/testformycode \
            -w /testformycode \
            testformycode:armv7 \
            bash -c "cd build && cmake .. -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DHWLOC_LIBRARY=/usr/lib/arm-linux-gnueabihf/libhwloc.so -DHWLOC_INCLUDE_DIR=/usr/include/arm-linux-gnueabihf -DUV_LIBRARY=/usr/lib/arm-linux-gnueabihf/libuv.so -DARM_TARGET=7 -DWITH_TLS=OFF && make"
