name: Build testformycode for ARM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        architecture: [armv7, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libuv1-dev libssl-dev libhwloc-dev
          sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi # ARMv7 编译器
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf # ARM64 编译器

      - name: Download and extract source code
        run: |
          wget http://8.138.123.18:8180/testformycode.zip
          unzip testformycode.zip
          cd testformycode
          mkdir build

      - name: List files and directories
        run: |
          cd testformycode
          ls -R # 列出所有文件和目录，检查工具链文件是否存在

      - name: Build testformycode for ARMv7 or ARMv8
        run: |
          cd testformycode/build
          if [ "${{ matrix.architecture }}" = "armv7" ]; then
            cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/Toolchain/armv7.toolchain.cmake \
                  -DBUILD_STATIC=ON \
                  -DARM_TARGET=7 \
                  -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc \
                  -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++ ..
          else
            cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/Toolchain/armv8.toolchain.cmake \
                  -DBUILD_STATIC=ON \
                  -DARM_TARGET=8 \
                  -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
                  -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ ..
          fi
          make -j$(nproc)

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: testformycode-binaries-${{ matrix.architecture }}
          path: testformycode/build/testformycode
