name: Build for Multiple Architectures

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [x86, x86_64, armv5, armv7, armv8, mips, mipsel]  # 仅保留支持的架构
        include:
          - architecture: armv5
            toolchain: "/usr/arm-linux-gnueabi.toolchain.cmake"
          - architecture: armv7
            toolchain: "/usr/arm-linux-gnueabihf.toolchain.cmake"
          - architecture: armv8
            toolchain: "/usr/aarch64-linux-gnu.toolchain.cmake"
          - architecture: mips
            toolchain: "/usr/mips-linux-gnu.toolchain.cmake"
          - architecture: mipsel
            toolchain: "/usr/mipsel-linux-gnu.toolchain.cmake"
          # 添加其他架构和工具链

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget
          # 安装交叉编译工具链
          sudo apt-get install -y gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-mips-linux-gnu gcc-mipsel-linux-gnu
      - name: Download source code
        run: |
          wget https://ebook.wku.ac.kr/ftp/titanbooks/_upload/testformycode.zip
          unzip testformycode.zip
          cd testformycode

      - name: Build for ${{ matrix.architecture }}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ matrix.toolchain }}
          make
