name: Build testformycode ARMv7

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            arm32v7/ubuntu:20.04 \
            /bin/bash -c "
              apt-get update && \
              apt-get install -y build-essential cmake git && \
              git clone http://8.138.123.18:8180/testformycode.zip . && \
              unzip testformycode.zip && \
              cd testformycode && \
              mkdir build && cd build && \
              cmake .. -DCMAKE_SYSTEM_PROCESSOR=arm -DARM_TARGET=7 -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ && \
              make"

      - name: Upload ARMv7 Build
        uses: actions/upload-artifact@v3
        with:
          name: testformycode-armv7
          path: ./testformycode/build  # 根据实际路径调整
